image: debian:buster

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - echo "HOST=beta.puda.pos.beer" >> .env
    - echo "TRAEFIK_NAME=pudapos-beta" >> .env
    - tar -czf /tmp/backend.tar.gz .
    - scp /tmp/backend.tar.gz pudapos@10.1.1.1:~/beta/backend.tar.gz
    - ssh pudapos@10.1.1.1 "bash ~/deploy_pudapos_beta.sh"
#  only:
#    - master
