image: docker.gitlab.blep.cz/blep.cz/pipenv-runner

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts

stages:
  - test
  - deploy

django:
  stage: test
  script:
    - cd pos
    - pip install -r requirements.txt
    - python manage.py test

beta-server:
  stage: deploy
  script:
    - echo "HOST=beta.puda.pos.beer" >> .env
    - echo "TRAEFIK_NAME=pudapos-beta" >> .env
    - sed -ie 's~^DEBUG=\(.*\)$~DEBUG=1~g' .env
    - tar -czf /tmp/backend.tar.gz .
    - scp /tmp/backend.tar.gz pudapos@10.1.1.1:~/beta/backend.tar.gz
    - ssh pudapos@10.1.1.1 "bash ~/deploy_pudapos_beta.sh"
  only:
    - master

test-server:
  stage: deploy
  script:
    - echo "HOST=test.puda.pos.beer" >> .env
    - echo "TRAEFIK_NAME=pudapos-test" >> .env
    - sed -ie 's~^DEBUG=\(.*\)$~DEBUG=1~g' .env
    - sed -ie 's~^VERSION=\(.*\)$~VERSION=\1-'"$CI_COMMIT_SHORT_SHA"'~g' .env
    - tar -czf /tmp/backend.tar.gz .
    - scp /tmp/backend.tar.gz pudapos@10.1.1.1:~/test/backend.tar.gz
    - ssh pudapos@10.1.1.1 "bash ~/deploy_pudapos_test.sh"
  except:
    - master
