image: docker.gitlab.blep.cz/blep.cz/pipenv-runner

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

stages:
  - test
  - deploy

.base_job:
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts

variables:
  PIP_REQUIREMENTS_FILE: pos/requirements.txt
  SAST_DEFAULT_ANALYZERS: "bandit,eslint,secrets"

license_scanning:
  variables:
    LICENSE_FINDER_CLI_OPTS: --pip-requirements-path=pos/requirements.txt

django:
  extends: .base_job
  stage: test
  script:
    - cd pos
    - pip install -r requirements.txt
    - python manage.py test

beta-server:
  extends: .base_job
  stage: deploy
  script:
    - echo "HOST=beta.puda.pos.beer" >> .env
    - echo "TRAEFIK_NAME=pudapos-beta" >> .env
    - sed -ie 's~^DEBUG=\(.*\)$~DEBUG=1~g' .env
    - sed -ie 's~^DEFAULT_PAGE_TITLE=\(.*\)$~DEFAULT_PAGE_TITLE=PUDA POS Beta~g' .env
    - tar -czf /tmp/backend.tar.gz .
    - scp /tmp/backend.tar.gz pudapos@evans.blep.cz:~/beta/backend.tar.gz
    - ssh pudapos@evans.blep.cz "bash ~/deploy_pudapos_beta.sh"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

test-server:
  extends: .base_job
  stage: deploy
  script:
    - echo "HOST=test.puda.pos.beer" >> .env
    - echo "TRAEFIK_NAME=pudapos-test" >> .env
    - sed -ie 's~^DEBUG=\(.*\)$~DEBUG=1~g' .env
    - sed -ie 's~^VERSION=\(.*\)$~VERSION=\1-'"$CI_COMMIT_SHORT_SHA"'~g' .env
    - sed -ie 's~^DEFAULT_PAGE_TITLE=\(.*\)$~DEFAULT_PAGE_TITLE=PUDA POS Test~g' .env
    - tar -czf /tmp/backend.tar.gz .
    - scp /tmp/backend.tar.gz pudapos@evans.blep.cz:~/test/backend.tar.gz
    - ssh pudapos@evans.blep.cz "bash ~/deploy_pudapos_test.sh"
  rules:
      - if: '$CI_MERGE_REQUEST_IID'
        when: never
      - if: '$CI_COMMIT_BRANCH != "master"'
        when: on_success
