version: '3.7'

services:
  web:
    build: ./pos
    command: python manage.py startweb 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/pos/static
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    networks:
      - puda
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=puda
      - POSTGRES_PASSWORD=puda
      - PUSTGRES_DB=puda
    networks:
      - puda
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/static
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - puda
  redis:
    image: redis:alpine
    networks:
      - puda

volumes:
  postgres_data:
  static_volume:

networks:
  puda:
