version: '3.7'

services:
  web:
    build: ./pos
    command: gunicorn puda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/pos/static/
      - ./pos/:/usr/src/pos/
    expose:
      - 8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    enevironment:
      - POSTGRES_USER=puda
      - POSTGRES_PASSWORD=puda
      - PUSTGRES_DB=puda_django
  nginx:
    build: ./nginx
    vokumes:
      - static_volume:/var/www/static/
    ports:
      - 1337:80
    depends:
      - web

volumes:
  postgres_data:
  static_volume:
